### PR TITLE
No item default name

### PR DESCRIPTION
**Pull request by bumi**
I find "item 1" quite ugly and I don't think that name gives any value over just no name

### CODE REVIEW

**Review by rolznz — CHANGES_REQUESTED** [review]
This change reveals a couple of issues:

- If you go to the cart the current item now looks buggy because it has no name (although I didn't put any effort styling here)
- If you enter a value, go to the cart, then back to the "/new" page and type a different amount and go to the cart again, it'll just add +1 to the quantity of the original value you typed (since the item name is currently used as the key)

**Comment by bumi** [comment]
For me it's actually a conceptual issue that an item is created when I just enter an amount and charge x sats. 

and I just fund it very ugly to communicate "item 1" to a customer.

**Comment by bumi** [comment]
but I also made my POS simple fork: https://github.com/bumi/pos-simple and removed that there.
so feel free to close this

**Comment by rolznz** [comment]
@bumi I think you have a good point, I just think we need to find a better solution that doesn't break this.

The simplest thing would be to just hide items that start with the default prefix from the invoice screen and invoice memo. What do you think?

**Comment by bumi** [comment]
> The simplest thing would be to just hide items that start with the default prefix from the invoice screen and invoice memo. What do you think?

I think throwing code at things is mostly not a good solution. 
now you would need to write again code that iterates through items and checks if they match some other string. 
lot's of complexity that will break at some point. 
and the next person not knowing all these details has a hard time reading the code and understanding the reasons and thus makes it hard to maintain and hard for new people to change things.

**Comment by rolznz** [comment]
Closing in favor of https://github.com/getAlby/pos/pull/29

**Pull request closed without merging**
